export const SET_CARDS = "SET_CARDS";
export const CARD_CHECKED_HANDLER = "CARD_CHECKED_HANDLER";
export const EDIT_MODE_ENABLED = "EDIT_MODE_ENABLED";
export const SAVE_CHANGES = "SAVE_CHANGES";
export const CANCEL_CHANGES = "CANCEL_CHANGES";
export const DELETE_CARDS_HANDLER = "DELETE_CARDS_HANDLER";
export const ADD_CARD_HANDLER = "ADD_CARD_HANDLER";
